version: '3.7'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=coasterranker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  service-coaster:
    build:
      context: ./rideit-service-coaster
      dockerfile: Dockerfile
    environment:
      - DB_HOST=jdbc:postgresql://host.docker.internal:5432/coasterranker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8080:8080
    container_name: service-coaster
    depends_on:
      - db
  
  service-comment:
    build:
      context: ./rideit-service-comment
      dockerfile: Dockerfile
    environment:
      - DB_HOST=jdbc:postgresql://host.docker.internal:5432/coasterranker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
    - 8081:8081
    container_name: service-comment
    depends_on:
      - db

  service-review:
    build:
      context: ./rideit-service-review
      dockerfile: Dockerfile
    environment:
      - DB_HOST=jdbc:postgresql://host.docker.internal:5432/coasterranker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
    - 8082:8082
    container_name: service-review
    depends_on:
      - db

  service-user:
    build:
      context: ./rideit-service-user
      dockerfile: Dockerfile
    environment:
      - DB_HOST=jdbc:postgresql://host.docker.internal:5432/coasterranker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
    - 8083:8083
    container_name: service-user
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000

  api:
    build:
      context: ./rideit-api
      dockerfile: Dockerfile
    volumes:
      - './api:/usr/src/app/api'
    container_name: api
    ports:
      - 4040:4040
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coasterranker
      - HOST=api
      - PORT=4040
      - SERVICE_COASTER_URI=http://host.docker.internal:8080
      - SERVICE_COMMENT_URI=http://host.docker.internal:8081
      - SERVICE_REVIEW_URI=http://host.docker.internal:8082
      - SERVICE_USER_URI=http://host.docker.internal:8083
      - JWT_EXPIRATION_MINUTES=5
      - JWT_SECRET=x
      - GOOGLE_OAUTH_REDIRECT_URI=http://localhost:3000/signin/redirect
      - GOOGLE_CLIENT_ID=768911286952-61g6ij1l4v0qpaahgll8goa32fd7k0ck.apps.googleusercontent.com
      - GOOGLE_SECRET=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
    depends_on:
      - service-coaster
      - service-comment
      - service-review
      - service-user
      - nginx

  client:
    build:
      context: ./rideit-client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app/client'
    container_name: client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://0.0.0.0:5000/api
      - NEXT_SERVER_API_URL=http://host.docker.internal:5000/api
    depends_on:
      - api

  data-setup:
    build:
      context: ./rideit-api
      dockerfile: Dockerfile.tools
    restart: "no"
    depends_on:
      - api
